### ISSUE TITLE
Stack use after scope after a syntax error

### ISSUE THREAD

**Issue by ProkopRandacek** [vtereshkov/umka-lang#210]
Hello,
Address sanitizer reports a stack use after scope for the following input:
```
const U=atan2(2,7
```

```
==136847==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffd9b949a20 at pc 0x55dc63470c77 bp 0x7ffd9b948f50 sp 0x7ffd9b948f48
READ of size 8 at 0x7ffd9b949a20 thread T0
    #0 0x55dc63470c76 in constCallBuiltin /home/prokop/source/umka-lang/build/../src/umka_const.c:230:44
    #1 0x55dc634bf241 in parseBuiltinMathCall /home/prokop/source/umka-lang/build/../src/umka_expr.c:651:9
    #2 0x55dc634bae73 in parseBuiltinCall /home/prokop/source/umka-lang/build/../src/umka_expr.c:1191:37
    #3 0x55dc634aec26 in parsePrimary /home/prokop/source/umka-lang/build/../src/umka_expr.c:1381:13
    #4 0x55dc634ad2b1 in parseDesignator /home/prokop/source/umka-lang/build/../src/umka_expr.c:1925:9
    #5 0x55dc635029df in parseFactor /home/prokop/source/umka-lang/build/../src/umka_expr.c:1985:13
    #6 0x55dc6350107f in parseTerm /home/prokop/source/umka-lang/build/../src/umka_expr.c:2106:5
    #7 0x55dc63500de1 in parseRelationTerm /home/prokop/source/umka-lang/build/../src/umka_expr.c:2145:9
    #8 0x55dc634fe8df in parseRelation /home/prokop/source/umka-lang/build/../src/umka_expr.c:2154:5
    #9 0x55dc634b4234 in parseLogicalTerm /home/prokop/source/umka-lang/build/../src/umka_expr.c:2180:5
    #10 0x55dc634b3004 in parseExpr /home/prokop/source/umka-lang/build/../src/umka_expr.c:2224:5
    #11 0x55dc6356ae61 in parseSingleDeclAssignmentStmt /home/prokop/source/umka-lang/build/../src/umka_stmt.c:239:5
    #12 0x55dc635676fe in parseDeclAssignmentStmt /home/prokop/source/umka-lang/build/../src/umka_stmt.c:303:9
    #13 0x55dc6347e046 in parseShortVarDecl /home/prokop/source/umka-lang/build/../src/umka_decl.c:635:5
    #14 0x55dc6347f797 in parseDecl /home/prokop/source/umka-lang/build/../src/umka_decl.c:687:26
    #15 0x55dc63494457 in parseDecls /home/prokop/source/umka-lang/build/../src/umka_decl.c:705:9
    #16 0x55dc6348555c in parseModule /home/prokop/source/umka-lang/build/../src/umka_decl.c:810:5
    #17 0x55dc63484479 in parseProgram /home/prokop/source/umka-lang/build/../src/umka_decl.c:824:22
    #18 0x55dc634587b4 in compilerCompile /home/prokop/source/umka-lang/build/../src/umka_compiler.c:206:5
    #19 0x55dc6342b038 in umkaCompile /home/prokop/source/umka-lang/build/../src/umka_api.c:107:9
    #20 0x55dc63a787f4 in LLVMFuzzerTestOneInput /home/prokop/source/umka-lang/build/../src/umka_fuzz.c:26:3
    #21 0x55dc6330c1b8 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) crtstuff.c
    #22 0x55dc6330cb10 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) crtstuff.c
    #23 0x55dc6330db21 in fuzzer::Fuzzer::MutateAndTestOne() crtstuff.c
    #24 0x55dc6330f4d7 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile> >&) crtstuff.c
    #25 0x55dc632f3264 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) crtstuff.c
    #26 0x55dc6332d7f7 in main (/home/prokop/source/umka-lang/build/umkafuzz+0x36f7f7)
    #27 0x7f4b3a7262cf  (/usr/lib/libc.so.6+0x232cf) (BuildId: 9c28cfc869012ebbd43cdb0f1eebcd14e1b8bdd8)
    #28 0x7f4b3a726389 in __libc_start_main (/usr/lib/libc.so.6+0x23389) (BuildId: 9c28cfc869012ebbd43cdb0f1eebcd14e1b8bdd8)
    #29 0x55dc632e2794 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

Address 0x7ffd9b949a20 is located in stack of thread T0 at offset 64 in frame
    #0 0x55dc634be6df in parseBuiltinMathCall /home/prokop/source/umka-lang/build/../src/umka_expr.c:628

  This frame has 2 object(s):
    [32, 40) 'type2' (line 640)
    [64, 72) 'constant2Val' (line 641) <== Memory access at offset 64 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope /home/prokop/source/umka-lang/build/../src/umka_const.c:230:44 in constCallBuiltin
Shadow bytes around the buggy address:
  0x1000337212f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100033721300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100033721310: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100033721320: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100033721330: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
=>0x100033721340: f8 f2 f2 f2[f8]f3 f3 f3 00 00 00 00 00 00 00 00
  0x100033721350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100033721360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100033721370: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100033721380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100033721390: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==136847==ABORTING
```

(found using the fuzzer from #209)

**Comment by vtereshkov** [comment]
Thank you @ProkopRandacek
