### ISSUE TITLE
Interpreter segfaults on pointer assignment

### ISSUE THREAD

**Issue by Mazdaywik** [vtereshkov/umka-lang#33]
Example:
```
type (
  P1 = ^S1
  P2 = ^S2

  S1 = struct {
    x: int
    next: P1
  }

  S2 = struct {
    x: int
    next: P2
  }
)

fn main() {
  var p1 : P1

  p1 = new(S2)
}
```
Download: [pointers.um.txt](https://github.com/vtereshkov/umka-lang/files/5718204/pointers.um.txt).

There are problem in implementation of structural type equivalence. Umka implements [structural type system](https://en.wikipedia.org/wiki/Structural_type_system), types are equivalent if its have same structure. Types `P1` and `P2` are equivalent by the specification ([Type compatibility](https://github.com/vtereshkov/umka-lang/blob/098d78c508bd1e78a4a51efb8bbbddfa01334aa1/spec.md#type-compatibility)), but type checker goes mad on recursive equivalence.

<details><summary>GDB proofs my opinion</summary>

```
D:\…\umka_0.4_x86-64_windows_mingw>gdb --args umka.exe pointers.um
GNU gdb (GDB) 7.6
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from D:\…\umka.exe...done.
(gdb) r
Starting program: D:\…\umka.exe pointers.um
[New Thread 5796.0x1770]
[New Thread 5796.0x25cc]
[New Thread 5796.0x2d9c]
[New Thread 5796.0x1ebc]

Program received signal SIGSEGV, Segmentation fault.
0x000000006ec53bce in typeEquivalent () from D:\…\libumka.dll
(gdb) bt
#0  0x000000006ec53bce in typeEquivalent () from D:\…\libumka.dll
#1  0x0000000000000000 in ?? ()
(gdb) q
A debugging session is active.

        Inferior 1 [process 5796] will be killed.

Quit anyway? (y or n) y
```

Interpreter fails at a function named `typeEquivalent()`.

</details>

Structural type system is very interesting!

![coolface.jpg](https://user-images.githubusercontent.com/1309859/102664588-30863880-4194-11eb-8a2e-653f26ce2af8.png)

**Comment by Mazdaywik** [comment]
🤦‍♂️
